[package]
name = "gagne-ton-papa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]

[dependencies]
gtp-lib = { path = "lib" }
nalgebra = "0.31.0"
colored = "2.0.0"